export const huggingFaceFreeModels = [
  {
    id: "hf:Qwen/Qwen3-0.6B",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "Qwen/Qwen3-0.6B",
    task: "text-generation",
    license: "apache-2.0",
    profile: "small-chat",
    runtime: ["huggingface-endpoint", "local-transformers", "text-generation-inference"],
    context_window: null,
    notes: "Small open-weight Qwen3 chat/text-generation model suitable for low-cost local or HF-backed testing.",
  },
  {
    id: "hf:Qwen/Qwen3-4B",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "Qwen/Qwen3-4B",
    task: "text-generation",
    license: "apache-2.0",
    profile: "balanced-chat",
    runtime: ["huggingface-endpoint", "local-transformers", "text-generation-inference"],
    context_window: null,
    notes: "Balanced open-weight Qwen3 model for chat and coding-adjacent tasks.",
  },
  {
    id: "hf:Qwen/Qwen3-8B",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "Qwen/Qwen3-8B",
    task: "text-generation",
    license: "apache-2.0",
    profile: "general-chat",
    runtime: ["huggingface-endpoint", "local-transformers", "text-generation-inference"],
    context_window: null,
    notes: "Popular open-weight Qwen3 model with broad chat/text-generation support.",
  },
  {
    id: "hf:Qwen/Qwen2.5-1.5B-Instruct",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "Qwen/Qwen2.5-1.5B-Instruct",
    task: "text-generation",
    license: "apache-2.0",
    profile: "small-instruct",
    runtime: ["huggingface-endpoint", "local-transformers", "text-generation-inference"],
    context_window: null,
    notes: "Small Apache-licensed instruct model for fast local testing.",
  },
  {
    id: "hf:Qwen/Qwen2.5-7B-Instruct",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "Qwen/Qwen2.5-7B-Instruct",
    task: "text-generation",
    license: "apache-2.0",
    profile: "general-instruct",
    runtime: ["huggingface-endpoint", "local-transformers", "text-generation-inference"],
    context_window: null,
    notes: "Strong open instruct baseline with high availability across HF-compatible runtimes.",
  },
  {
    id: "hf:openai/gpt-oss-20b",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "openai/gpt-oss-20b",
    task: "text-generation",
    license: "apache-2.0",
    profile: "large-reasoning",
    runtime: ["huggingface-endpoint", "vllm", "text-generation-inference"],
    context_window: null,
    notes: "Open-weight Apache-licensed model for higher quality reasoning when sufficient GPU is available.",
  },
  {
    id: "hf:deepseek-ai/DeepSeek-R1",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "deepseek-ai/DeepSeek-R1",
    task: "text-generation",
    license: "mit",
    profile: "large-reasoning",
    runtime: ["huggingface-endpoint", "vllm", "text-generation-inference"],
    context_window: null,
    notes: "Open reasoning model; practical use usually requires a hosted or GPU runtime.",
  },
  {
    id: "hf:microsoft/Phi-3-small-8k-instruct",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "microsoft/Phi-3-small-8k-instruct",
    task: "text-generation",
    license: "mit",
    profile: "small-instruct",
    runtime: ["huggingface-endpoint", "local-transformers"],
    context_window: 8192,
    notes: "MIT-licensed small instruct model with code and multilingual tags.",
  },
  {
    id: "hf:microsoft/Phi-3-small-128k-instruct",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "microsoft/Phi-3-small-128k-instruct",
    task: "text-generation",
    license: "mit",
    profile: "long-context-instruct",
    runtime: ["huggingface-endpoint", "local-transformers"],
    context_window: 131072,
    notes: "MIT-licensed long-context instruct model for local/HF experiments.",
  },
  {
    id: "hf:Tiiny/SmallThinker-4BA0.6B-Instruct",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "Tiiny/SmallThinker-4BA0.6B-Instruct",
    task: "text-generation",
    license: "apache-2.0",
    profile: "tiny-reasoning",
    runtime: ["huggingface-endpoint", "local-transformers"],
    context_window: null,
    notes: "Very small Apache-licensed reasoning/instruct model for smoke tests and constrained devices.",
  },
  {
    id: "hf:SmallDoge/Doge-160M-Instruct",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "SmallDoge/Doge-160M-Instruct",
    task: "question-answering",
    license: "apache-2.0",
    profile: "tiny-qa",
    runtime: ["huggingface-endpoint", "local-transformers"],
    context_window: null,
    notes: "Tiny Apache-licensed instruct/QA model for health checks and low-resource tests.",
  },
  {
    id: "hf:unsloth/Mistral-Small-24B-Instruct-2501-GGUF",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "unsloth/Mistral-Small-24B-Instruct-2501-GGUF",
    task: "text-generation",
    license: "apache-2.0",
    profile: "local-gguf-instruct",
    runtime: ["local-gguf", "llama.cpp", "ollama-compatible"],
    context_window: null,
    notes: "Apache-licensed GGUF option for local llama.cpp/Ollama-style serving.",
  },
  {
    id: "hf:unsloth/Mistral-Small-24B-Instruct-2501-unsloth-bnb-4bit",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "unsloth/Mistral-Small-24B-Instruct-2501-unsloth-bnb-4bit",
    task: "text-generation",
    license: "apache-2.0",
    profile: "quantized-instruct",
    runtime: ["huggingface-endpoint", "local-transformers", "bitsandbytes"],
    context_window: null,
    notes: "4-bit quantized Mistral Small instruct variant for GPU-constrained deployments.",
  },
  {
    id: "hf:byteshape/Devstral-Small-2-24B-Instruct-2512-GGUF",
    provider: "huggingface",
    upstream_provider: "openai-compatible",
    repo: "byteshape/Devstral-Small-2-24B-Instruct-2512-GGUF",
    task: "text-generation",
    license: "apache-2.0",
    profile: "local-gguf-coding",
    runtime: ["local-gguf", "llama.cpp", "ollama-compatible"],
    context_window: null,
    notes: "GGUF coding-oriented local model candidate from the Devstral family.",
  },
];

export function listModels({ provider } = {}) {
  const data = provider ? huggingFaceFreeModels.filter((model) => model.provider === provider) : huggingFaceFreeModels;
  return {
    object: "list",
    data: data.map((model) => ({ object: "model", ...model })),
  };
}

export function findModel(modelId) {
  return huggingFaceFreeModels.find((model) => model.id === modelId || model.repo === modelId);
}
