apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: z-trading
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - services.yaml
  - workloads-disabled.yaml
  - networkpolicy.yaml
