apiVersion: v1
kind: Service
metadata:
  name: ztrader-intelligence
spec:
  selector:
    app.kubernetes.io/name: ztrader-intelligence
  ports:
    - name: http
      port: 8218
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: zksato
spec:
  selector:
    app.kubernetes.io/name: zksato
  ports:
    - name: http
      port: 9569
      targetPort: http
